### ISSUE TITLE
HX8347G problem

### ISSUE THREAD

**Issue by wallace09** [prenticedavid/MCUFRIEND_kbv#11]
I'm trying to use a 2.8 "TFT screen shield with arduino uno, 
 but I could not write anything on the screen, I tried the library of MCU_KBV and I am waiting for your help 
Screen: MCUFRIEND HX8347G
Note: the SD card on the screen is working

![17201292_10155036403959144_7139475389576506989_n](https://cloud.githubusercontent.com/assets/26308636/23763250/7eea2aa0-0501-11e7-8e84-acb90fbde3c7.jpg)
![17190901_10155036403969144_603658339160435241_n](https://cloud.githubusercontent.com/assets/26308636/23763257/83ef37a2-0501-11e7-92a2-aa1412fd2ed5.jpg)

**Comment by prenticedavid** [comment]
Woo-hoo.  Mcufriend is "almost" becoming helpful.    e.g. you probably have HX8347-G 
Other Shields are appearing with a sticky paper label with a controller number.

In MCUFRIEND_kbv.cpp uncomment the SUPPORT_8347D macro.

David.

**Comment by wallace09** [comment]
Thank you so much.
You're king
