### ISSUE TITLE
2.2" Display showing white screen

### ISSUE THREAD

**Issue by smah1980** [prenticedavid/MCUFRIEND_kbv#112]
Hello, 
I am getting the following output while reading the reg. 
also tried every 320x240 driver given in mcufriend_how_to.txt
I have RM68130 display. not able to find any help. can you spot some light on it.
I am using Arduino Mego 2560, tried to connect data with pin 22-29 as well as 8,9,10,11,4,13,6,7 while 
// CS                 -- A3
// RS                 -- A2
// WR                -- A1
// RD                 -- 3.3V also tried with A0
and Reset with A4 as well as reset pin

but nothing worked.

![image](https://user-images.githubusercontent.com/31177036/66072785-249e5e80-e56f-11e9-8c69-8342a8c1cb92.png)

reg(0x0000) C0 C0	ID: ILI9320, ILI9325, ILI9335, ...
reg(0x0004) C4 C4 E4 E4	Manufacturer ID
reg(0x0009) C9 C9 E9 E9 E9	Status Register
reg(0x000A) CA CA	Get Power Mode
reg(0x000C) CC CC	Get Pixel Format
reg(0x0061) E1 E1	RDID1 HX8347-G
reg(0x0062) E2 E2	RDID2 HX8347-G
reg(0x0063) E3 E3	RDID3 HX8347-G
reg(0x0064) E4 E4	RDID1 HX8347-A
reg(0x0065) E5 E5	RDID2 HX8347-A
reg(0x0066) E6 E6	RDID3 HX8347-A
reg(0x0067) E7 E7	RDID Himax HX8347-A
reg(0x0070) F0 F0	Panel Himax HX8347-A
reg(0x00A1) E1 E1 E1 E1 E1	RD_DDB SSD1963
reg(0x00B0) F0 F0	RGB Interface Signal Control
reg(0x00B4) F4 F4	Inversion Control
reg(0x00B6) F6 F6 F6 F6 F6	Display Control
reg(0x00B7) F7 F7	Entry Mode Set
reg(0x00BF) FF FF FF FF FF FF	ILI9481, HX8357-B
reg(0x00C0) C0 C0 E0 E0 E0 E0 E0 E0 E0	Panel Control
reg(0x00C8) C8 C8 E8 E8 E8 E8 E8 E8 E8 E8 E8 E8 E8	GAMMA
reg(0x00CC) CC CC	Panel Control
reg(0x00D0) D0 D0 F0	Power Control
reg(0x00D2) D2 D2 F2 F2 F2	NVM Read
reg(0x00D3) D3 D3 F3 F3	ILI9341, ILI9488
reg(0x00D4) D4 D4 F4 F4	Novatek ID
reg(0x00DA) DA DA	RDID1
reg(0x00DB) DB DB	RDID2
reg(0x00DC) DC DC	RDID3
reg(0x00E0) E0 E0 E0 E0 E0 E0 E0 E0 E0 E0 E0 E0 E0 E0 E0 E0	GAMMA-P
reg(0x00E1) E1 E1 E1 E1 E1 E1 E1 E1 E1 E1 E1 E1 E1 E1 E1 E1	GAMMA-N
reg(0x00EF) EF EF EF EF EF EF	ILI9327
reg(0x00F2) F2 F2 F2 F2 F2 F2 F2 F2 F2 F2 F2 F2	Adjust Control 2
reg(0x00F6) F6 F6 F6 F6	Interface Control

after running graphicstest_kbv

its prints on serial monitor
ID = 0xD3D3

could you please help
Thanks

**Comment by prenticedavid** [comment]
I have replied on the Arduino Displays Forum.
