### ISSUE TITLE
stm32103fc8 with lcd3.5

### ISSUE THREAD

**Issue by Jamal-13** [prenticedavid/MCUFRIEND_kbv#126]
Hello 
How can I take screenshot for all things on screen ?
and How can I replay show it second time?

**Comment by Jamal-13** [comment]
and How can I replay show it second time?

**Comment by prenticedavid** [comment]
You use readGRAM() to read the screen memory.   And save it to a  file on SD card.

Either as a RAW file containing W x H pixels.
Or as a .BMP format file which will make the file readable on your PC.

The first job is to make sure that you can read and write to SD card e.g. with showBMP_uno_kbv.ino

David.
