### ISSUE TITLE
[Feature request] UTouch & UTFT_Buttons support?

### ISSUE THREAD

**Issue by information-security** [prenticedavid/MCUFRIEND_kbv#13]
Hi,

when using UTFT library we can use UTouch and UTFT_Buttons libraries which are very useful. Can you please implement similar libraries which will work with yours?

Thanks in advance

**Comment by prenticedavid** [comment]
The Mcufriend Uno Shields have a resistive Touch Screen.   You use the "TouchScreen,h" library from Adafruit.   I suggest that you edit it to use a sensible value for NUMSAMPLES.

I put a new version of the TouchScreen Calibration sketch in the examples folder yesterday.
The regular Adafruit_GFX_Button class comes with the Adafruit_GFX library.   MCUFRIEND_kbv programs work just fine with any of the GFX features.

If you are using a Mcufriend Mega Shield as a SPECIAL,   these have an XPT2046 Touch Controller chip.    You can use the UTouch or URTouch library or any library that supports bit-banging a XPT2046.

David.
