### ISSUE TITLE
MCUFRIEND_kbv::readID returns wrong ID

### ISSUE THREAD

**Issue by CSalih** [prenticedavid/MCUFRIEND_kbv#132]
**Describe the bug :boom:**
If i upload the `font_simple` example to my Teensy nothing will displayed. After some time i figure out that readID returns a wrong ID.  To make the Display working i have to define `uint32_t ID = 0x9684`.

**To Reproduce :repeat:**
1. Type in `setup()`:   
``` c
uint16_t ID = tft.readID();
Serial.println(ID, HEX);
```
2. Execute

**Actual behavior :thumbsdown:**
ID is 0x9494

**Expected behavior :pray:**
ID should be 0x9486

**Environment :earth_americas:**
 - Board: Teensy 3.5
 - Version: 2.9.8
 - Display: ILI9486

**Additional context :gem:**
LCD_ID_readreg:
```
Read Registers on MCUFRIEND UNO shield
controllers either read as single 16-bit
e.g. the ID is at readReg(0)
or as a sequence of 8-bit values
in special locations (first is dummy)
reg(0x0000) 00 00	ID: ILI9320, ILI9325, ILI9335, ...
reg(0x0004) 00 54 80 66	Manufacturer ID
reg(0x0009) 00 00 61 00 00	Status Register
reg(0x000A) 00 08	Get Power Mode
reg(0x000C) 00 66	Get Pixel Format
reg(0x0061) 00 00	RDID1 HX8347-G
reg(0x0062) 00 00	RDID2 HX8347-G
reg(0x0063) 00 00	RDID3 HX8347-G
reg(0x0064) 00 00	RDID1 HX8347-A
reg(0x0065) 00 00	RDID2 HX8347-A
reg(0x0066) 00 00	RDID3 HX8347-A
reg(0x0067) 00 00	RDID Himax HX8347-A
reg(0x0070) 00 00	Panel Himax HX8347-A
reg(0x00A1) 00 93 30 93 30	RD_DDB SSD1963
reg(0x00B0) 00 00	RGB Interface Signal Control
reg(0x00B4) 00 00	Inversion Control
reg(0x00B6) 00 02 02 3B 3B	Display Control
reg(0x00B7) 00 00	Entry Mode Set
reg(0x00BF) 00 00 00 00 00 00	ILI9481, HX8357-B
reg(0x00C0) 00 0E 0E 0E 0E 0E 0E 0E 0E	Panel Control
reg(0x00C8) 00 00 00 00 00 00 00 00 00 00 00 00 00	GAMMA
reg(0x00CC) 00 04	Panel Control
reg(0x00D0) 00 00 00	Power Control
reg(0x00D2) 00 00 00 00 00	NVM Read
reg(0x00D3) 00 00 94 86	ILI9341, ILI9488
reg(0x00D4) 00 00 00 00	Novatek ID
reg(0x00DA) 00 54	RDID1
reg(0x00DB) 00 00	RDID2
reg(0x00DC) 00 66	RDID3
reg(0x00E0) 00 03 21 13 0E 07 0D 7E D7 19 07 1A 08 0B 3A 03	GAMMA-P
reg(0x00E1) 00 0B 35 2B 0D 04 0F 44 29 69 0D 0A 01 26 07 06	GAMMA-N
reg(0x00EF) 00 00 00 10 60 40	ILI9327
reg(0x00F2) 00 18 A3 12 02 B2 12 DF 00 00 00 00	Adjust Control 2
reg(0x00F6) 00 00 80 66	Interface Control
```

**Comment by prenticedavid** [comment]
Thanks for the feedback.

> 
    Board: Teensy 3.5
    Version: 2.9.8
    Display: ILI9486

You appear to have a readID() failure but all the write commands work.

I don't have a Teensy 3.5 so there is a bit of timing guesswork.   Especially if you overclock.

Please can you try the current Beta i.e. the "master Branch".
Leave IDE.  Delete current library directory.  Start IDE.  Download ZIP from GitHub. Install from ZIP.  

Edit utility/mcufriend_shield.h

```
#elif defined(__MK64FX512__) // Teensy3.5 120MHz thanks to PeteJohno
#define WRITE_DELAY { WR_ACTIVE4; }
#define IDLE_DELAY  { WR_IDLE; }
#define READ_DELAY  { RD_ACTIVE8; }
```

Experiment with the delay macros.   e.g. increase until reliable or reduce until you get glitches.
Rinse and repeat with overclocking and underclocking.

Report back.   It is about time that I issue a new Release.

David.
