### ISSUE TITLE
Improved connection to Mega 2560

### ISSUE THREAD

**Issue by gboado** [prenticedavid/MCUFRIEND_kbv#138]
Hi. I needed to use the PWM ports which are in use by the current default shield connection of the parallel display to an Arduino Mega 2560, so I modified the file mcufriend_shield.h to handle a display connected to PORTA and PORTC. So far, it works like a charm (I need a cable to connect both boards). In addition to the more efficient use of the available ports, the speed of the library is significantly enhanced, since the data port is directly connected to a CPU I/O port and control signals are all together connected to another port.
Are you interested in these modifications or should I keep them private?

**Comment by prenticedavid** [comment]
Surely there have been SPECIALs since the beginning of time e.g.
```
//#define USE_MEGA_8BIT_PROTOSHIELD
//#define USE_MEGA_8BIT_SHIELD      // 4.7sec Mega2560 Shield
//#define USE_MEGA_8BIT_PORTC_SHIELD // 4.7sec Mega2560 Shield
//#define USE_MEGA_16BIT_SHIELD     // 2.14sec Mega2560 Shield 
```

Obviously you would not want to put any of these into mcufriend_shield.h unless there was a ready-made Arduino board with suitable headers.

David.
