### ISSUE TITLE
ili9488spi esp32

### ISSUE THREAD

**Issue by clear-sky** [prenticedavid/MCUFRIEND_kbv#155]
hi dear david
i am trying to run this lcd on esp32 in arduino
http://www.lcdwiki.com/3.5inch_SPI_Module_ILI9488_SKU:MSP3520
i have installed esp32 package from here(stable release)
https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md
and selected esp32dev module from board manager
and tried to use your repo 
https://github.com/prenticedavid/LCDWIKI_SPI
but have two problems
1-ili9488 is not supported
2-in my project ili 9488 reset pin is connected to EN pin(esp32) due to hardware limitation i can not use other pin please tell me how configure it in this line 
LCDWIKI_SPI mylcd(ILI9488,10,9,EN,22);

**Comment by prenticedavid** [comment]
The TFT should work fine with TFT_eSPI.   Bodmer has a ready made User Setup e.g. Setup21_ILI9488.h
I suggest that you follow the same wiring.

I suspect that the LcdWiki code will work but would be painful.

This is "Issues" for MCUFRIEND_kbv
You should ask questions on Arduino Forums

David.

**Comment by clear-sky** [comment]
thanks
