### ISSUE TITLE
Angle parameter for rectangles...

### ISSUE THREAD

**Issue by AntonioFromBrazil** [prenticedavid/MCUFRIEND_kbv#159]
David, what about implement a angle parameter for drawRect and fillRect functions ? I know it is not easy specially in fillRect but it will be very usefull... Tks, Antonio

**Comment by prenticedavid** [comment]
I inherit Graphics methods from Adafruit_GFX.    I do not want to add any other basic methods.

You can draw any quadrilateral with two trangles.

The only possible candidate for extra methods would be arc() and filledArc()

David.

**Comment by AntonioFromBrazil** [comment]
Two inverted triangles is a cure for my headache !!! Thanks for simple and great idea !!!
