### ISSUE TITLE
Axis Rotation

### ISSUE THREAD

**Issue by MihirPatel96** [prenticedavid/MCUFRIEND_kbv#32]
As I try to draw, the pen traces left to right but the display outputs it from right to left at the bottom of the screen. Whats the issue? it seems like an issue of inverted axis . How to solve it?

**Comment by prenticedavid** [comment]
From the mcufriend_how_to.txt:

> 12. These Mcufriend-style shields tend to have a resistive TouchScreen on A1, 7, A2, 6 but are not always the same rotation of direction.
>     The TouchScreen_Calibr_native.ino sketch wiil diagnose Touch Pins, do Calibration, report to Serial Terminal.
> 	The Calibration should work with the TouchScreen.h library from Adafruit.
> 	You can always copy the local TouchScreen_kbv.h library from sketch to the global user libraries folder.
> 

Note that you should use the TouchScreen_Calibr_native sketch from the current Beta.
Or download it from [https://forum.arduino.cc/index.php?topic=366304.msg2524865#msg2524865](url)

David.
