### ISSUE TITLE
2.8" Display not supported

### ISSUE THREAD

**Issue by Noordmeep** [prenticedavid/MCUFRIEND_kbv#72]
I've just bought 2 screens and the driver doesn't support the displays.
As documented the output from the serial is placed below.

Please help me to get the display to work.

Regads,

Hans Sietsema

Serial output:
Read Registers on MCUFRIEND UNO shield
controllers either read as single 16-bit
e.g. the ID is at readReg(0)
or as a sequence of 8-bit values
in special locations (first is dummy)

reg(0x0000) 00 D3	ID: ILI9320, ILI9325, ILI9335, ...
reg(0x0004) 04 D7 04 D7	Manufacturer ID
reg(0x0009) 08 DB 08 DB 08	Status Register
reg(0x000A) 08 08	Get Power Mode
reg(0x000C) 0C 0C	Get Pixel Format
reg(0x0061) 20 20	RDID1 HX8347-G
reg(0x0062) 20 20	RDID2 HX8347-G
reg(0x0063) 20 20	RDID3 HX8347-G
reg(0x0064) 24 24	RDID1 HX8347-A
reg(0x0065) 24 24	RDID2 HX8347-A
reg(0x0066) 24 24	RDID3 HX8347-A
reg(0x0067) 24 24	RDID Himax HX8347-A
reg(0x0070) 20 20	Panel Himax HX8347-A
reg(0x00A1) 20 20 20 20 20	RD_DDB SSD1963
reg(0x00B0) 20 20	RGB Interface Signal Control
reg(0x00B4) 24 24	Inversion Control
reg(0x00B6) 24 24 24 24 24	Display Control
reg(0x00B7) 24 24	Entry Mode Set
reg(0x00BF) 2C 2C 2C 2C 2C 2C	ILI9481, HX8357-B
reg(0x00C0) 00 00 00 00 00 00 00 00 00	Panel Control
reg(0x00C8) 1A 0A 1A 0A 1A 0A 1A 0A 1A 0A 1A 0A 1A	GAMMA
reg(0x00CC) 0C 0C	Panel Control
reg(0x00D0) 00 00 00	Power Control
reg(0x00D2) 00 00 00 00 00	NVM Read
reg(0x00D3) 00 00 00 00	ILI9341, ILI9488
reg(0x00D4) 04 04 04 04	Novatek ID
reg(0x00DA) 08 08	RDID1
reg(0x00DB) 08 08	RDID2
reg(0x00DC) 0C 0C	RDID3
reg(0x00E0) 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20	GAMMA-P
reg(0x00E1) 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20	GAMMA-N
reg(0x00EF) 2C 2C 2C 2C 2C 2C	ILI9327
reg(0x00F2) 20 20 20 20 20 20 20 20 20 20 20 20	Adjust Control 2
reg(0x00F6) 24 24 24 24	Interface Control

**Comment by prenticedavid** [comment]
It is always wise to post a link to your display e.g. Ebay sale.

I do not know what make or model.   It looks like a 9320 style controller.

Have you tried forcing tft.begin(0x9320) ?
It is probably better to post links, photos, comments on Arduino Forum.

David.

**Comment by Noordmeep** [comment]
OK thank youfor that comment.
I've bought the display via Wish.
https://www.wish.com/product/5b3608e17beacb052637efe6

After I forced the 0x9320 there was no change. The display sort of blinks from white to a slightly darker white.
When I use the diagnose tft support I get the following responce:
Diagnose whether this controller is supported
There are FAQs in extras/mcufriend_how_to.txt

tft.readID() finds: ID = 0xD3

MCUFRIEND_kbv version: 2.9.8


This ID is not supported
look up ID in extras/mcufriend_how_to.txt
you may need to edit MCUFRIEND_kbv.cpp
to enable support for this ID
e.g. #define SUPPORT_8347D

New controllers appear on Ebay often
If your ID is not supported
run LCD_ID_readreg.ino from examples/
Copy-Paste the output from the Serial Terminal
to a message in Displays topic on Arduino Forum
or to Issues on GitHub

Note that OPEN-SMART boards have diff pinout
Edit the pin defines in LCD_ID_readreg to match
Edit mcufiend_shield.h for USE_SPECIAL
Edit mcufiend_special.h for USE_OPENSMART_SHIELD_PINOUT


Hans

**Comment by Noordmeep** [comment]
Hello David,

Sorry I did read you posts and looked @ the pinning. It looked to be OK. So thats why I posted this message.
Sorry for the site. I forgot it only shows when your logged on.
I'fe taken some pictures so hopefully this is more clear.

Regards,  Hans
![img_20181209_213028](https://user-images.githubusercontent.com/24738221/49702686-3affb600-fbfb-11e8-9065-97b50e8f8fd0.jpg)
![img_20181209_213058](https://user-images.githubusercontent.com/24738221/49702687-3affb600-fbfb-11e8-9dea-7c6e1d59360a.jpg)

**Comment by prenticedavid** [comment]
Thanks for the photos.    That is the first that I have seen an Open-Smart with Renesas R61580 controller!

Note that OPEN-SMART boards have diff pinout
Edit MCUFRIEND_kbv.cpp for #define SUPPORT_1580
Edit mcufiend_shield.h for #define USE_SPECIAL
Edit mcufiend_special.h for #define USE_OPENSMART_SHIELD_PINOUT

I do not have any R61580.   It is a 9320 style controller.   It can NOT do Band Scroll.
Please let me know how you get on.

David.
