### ISSUE TITLE
change LCD_RST pin from A4 to A6  on Arduino Uno

### ISSUE THREAD

**Issue by stephengrenfell** [prenticedavid/MCUFRIEND_kbv#99]
I want to use 3,5" display with an Arduino Uno, but I also want to use the A4 and A5 pins for I2C.  Pin A4 is used for LCD_RST, so I want to use another port pin for the LCD reset (such as pin A6).

How can I do this ?.

Thanks.

**Comment by prenticedavid** [comment]
I have described the procedure several times on the Arduino Forum.    Google for "MCUFRIEND_kbv I2C"

You can not use A6 for LCD_RST because A6 on a mega328P is Analog-only pin.

David.
